default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= Rails.application.credentials[:postgres][:username] %>
  password: <%= Rails.application.credentials[:postgres][:password] %>
  host: <%= Rails.application.credentials[:postgres][:host] %>
  port: <%= Rails.application.credentials[:postgres][:port] %>

development:
  <<: *default
  database: development_db



test:
  <<: *default
  database: test_suite_db



production:
  <<: *default
  database:  production_db

